---
#System Settings
php_modules: [ 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]

#MySQL Settings
mysql_root_password: "password"
mysql_db: "wordpress"
mysql_user: "brianlam"
mysql_password: "password"

#HTTP Settings
http_host: "3.228.23.150"
http_conf: "aws.conf"
http_port: "80"
